name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1.2.0
        with:
          jvm: temurin:1.21
          apps: sbt
      - uses: coursier/cache-action@v6.3

      - uses: actions/setup-node@v1
        with:
          node-version: "22.15.0"
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@10.9.2

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          #strip `v` prefix
          strip_v: true

      # This env variable is used when we do Docs Publish
      - name: Set JITPACK_VERSION environment variable
        run: echo "JITPACK_VERSION=${{steps.tag.outputs.tag}}" >> $GITHUB_ENV

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Test
        run: npm run test

      - name: Docs Publish
        run: |
          echo 'echo $RELEASE_TOKEN' > /tmp/.git-askpass
          chmod +x /tmp/.git-askpass
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Action"
          sbt clean makeSite ghpagesPushSite
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_ASKPASS: /tmp/.git-askpass

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-release
